from fastapi import APIRouter, HTTPException, Request, Depends
from schemas.task import TaskCreate
from services.auth_service import decode_token
from repos.task_repo import create_task_record, get_tasks_by_user, create_subtask, update_subtask_status, get_subtasks_for_today_all, create_user_notification, update_plan_approval_status
from graph.workflow import ai_graph
from repos.database import get_db_connection
import json
from datetime import datetime

router = APIRouter(prefix="/api")

async def get_current_user(request: Request):
    token = request.headers.get("Authorization")
    if not token:
        raise HTTPException(status_code=401, detail="Not authorized")
    return decode_token(token)

@router.post("/approve-plan")
async def approve_plan(request: Request, payload: dict = Depends(get_current_user)):
    data = await request.json()
    task_id = data.get("task_id")
    
    if not task_id:
        raise HTTPException(status_code=400, detail="Missing task_id")

    user_id = payload.get("id")

    conn = get_db_connection()
    from psycopg2.extras import RealDictCursor
    cursor = conn.cursor(cursor_factory=RealDictCursor)
    try:
        cursor.execute(
            "SELECT title, description, time, ai_plan_json FROM tasks WHERE id = %s AND user_id = %s",
            (task_id, user_id)
        )
        task = cursor.fetchone()
        if not task or not task['ai_plan_json']:
            raise HTTPException(status_code=404, detail="Task or plan not found")
        
        plan_data = task['ai_plan_json']
        if isinstance(plan_data, str):
            plan_data = json.loads(plan_data)
            
        # final_plan contains the stringified JSON from LangGraph
        final_plan_str = plan_data.get("final_plan", "")
        subtasks_list = plan_data.get("subtasks", []) if isinstance(plan_data, dict) else []

        try:
            if isinstance(final_plan_str, str):
                final_plan_obj = json.loads(final_plan_str)
            else:
                final_plan_obj = final_plan_str
            if isinstance(final_plan_obj, dict) and not subtasks_list:
                subtasks_list = final_plan_obj.get("subtasks", [])
        except Exception as e:
            print(f"Error parsing final_plan: {e}")
            subtasks_list = subtasks_list or []

        if not subtasks_list:
            # Fallback: create a single subtask so routines still show up
            subtasks_list = [{
                "subtask": task.get("title") or "Main Task",
                "description": task.get("description") or "Complete the task",
                "time_to": (task.get("time") or "00:00:00")
            }]

        for st in subtasks_list:
            # Use the time_to generated by AI, which should be incremental HH:MM
            time_to = st.get('time_to')
            if time_to and ":" in time_to:
                parts = time_to.split(':')
                if len(parts) == 2:
                    time_to = f"{parts[0].zfill(2)}:{parts[1].zfill(2)}:00"
            else:
                time_to = task['time'] # Fallback
                
            create_subtask(task_id, st.get('subtask'), st.get('description'), time_to)
        
        update_plan_approval_status(task_id, True)
        create_user_notification(user_id, f"Plan approved and subtasks scheduled for task: {task_id}")
        return {"status": "success", "message": "Plan approved and subtasks created"}
    except Exception as e:
        print(f"Approval Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        cursor.close()
        conn.close()

@router.post("/subtasks/{subtask_id}/toggle")
async def toggle_subtask(subtask_id: int, request: Request, payload: dict = Depends(get_current_user)):
    data = await request.json()
    is_completed = data.get("is_completed")
    
    from repos.task_repo import update_subtask_status, check_and_update_task_status
    update_subtask_status(subtask_id, is_completed)
    task_completed = check_and_update_task_status(subtask_id)
    
    return {"status": "success", "task_completed": task_completed}

@router.get("/routine")
async def get_daily_routine_data(payload: dict = Depends(get_current_user)):
    user_id = payload.get("id")
    
    from repos.task_repo import get_hierarchical_routine
    tasks = get_hierarchical_routine(user_id)
    return {"routine": tasks}

@router.post("/tasks")
async def create_task(task_data: TaskCreate, payload: dict = Depends(get_current_user)):
    user_id = payload.get("id")
    
    # AI Plan Generation using LangGraph
    try:
        # Get current time for incremental scheduling with special rounding:
        # 0-19 -> 00, 20-40 -> 30, >40 -> next hour :00
        now = datetime.now()
        h, m = now.hour, now.minute
        if m < 20:
            m = 0
        elif 20 <= m <= 40:
            m = 30
        else:
            m = 0
            h = (h + 1) % 24
        now_time = f"{h:02d}:{m:02d}"
        
        ai_result = await ai_graph.ainvoke({
            "title": task_data.title, 
            "description": task_data.description or "",
            "current_time": now_time,
            "deadline": task_data.time, # The time part of the deadline
            "plans": [],
            "final_plan": ""
        })
            
        ai_plan_data = {"final_plan": ai_result["final_plan"]}
        ai_plan_json = json.dumps(ai_plan_data)
    except Exception as e:
        print(f"AI Generation Error: {e}")
        ai_plan_json = json.dumps({"error": "AI planning failed", "details": str(e)})

    # Use the provided time for task record creation
    success = create_task_record(
        task_data.title, 
        task_data.description, 
        user_id, 
        task_data.deadline_date, 
        task_data.time,
        task_data.status, 
        ai_plan_json
    )
    
    if success:
        return {"status": "success", "message": "Task and AI Plan created successfully"}
    raise HTTPException(status_code=500, detail="Failed to create task")

@router.get("/tasks")
async def get_all_tasks(payload: dict = Depends(get_current_user)):
    user_id = payload.get("id")
    return get_tasks_by_user(user_id)
